### ISSUE TITLE
Missing validation logic

### ISSUE THREAD

**Issue by lamine2000** [tors42/chariot#10]
Hi,
I've noticed that there is a lack of range and value validation on certain method arguments whithin the SDK. This absence of validation can lead to field validation errors during runtime when we unintentionally send incorrect requests (that aren't regarded as bad requests until reaching lichess API). Here are some examples:

- The ArenaBuilder::conditionMinRating method should only accept values within the range of 1000 to 2600 ELO, with a step of 100.
- The ArenaBuilder::name method should only accept strings with a length between 2 and 30 characters.
- The ArenaBuilder::conditionMinRatedGames should only accept one of the following values: {0, 5, 10, 15, 20, 30, 40, 50, 75, 100, 150, 200}.
- ...
In some cases, the method's documentation provides information about the expected value range or specific values, while in others, there is no indication. It can be counterproductive to have to meticulously refer to both the documentation and the SDK to ensure we're using the API correctly.

I have a few questions regarding this:
-  Was this lack of validation intentionally left as-is, and if so, would you like me to help ensure consistency by submitting a pull request?
-  If this lack of validation was not intentional, would you like me to submit a pull request that simply adds range validations and enums to these methods? This way, any deviation from the specified ranges or values would result in an early compile-time error.

(PS: I'm a fan of your work ! As a Junior Backend Developer, I find it really interesting to see the new java features used in actual projects. 💯 )

**Comment by tors42** [comment]
Hi!
Cool that you've checked out the logic! Hope you didn't look too closely at all the embarrassing parts.. ;)

One big win with letting server side perform the validation,
is to not need to maintain the set of valid values (which may change over time, intentionally or unintentionally (sometimes the Lichess API documentation is also out of date etc etc)). :sweat_smile: 

If I was in control of the server side too, I'd be much more eager to add the validation client side too, as I would always know when the valid values change.
That said, it is an awesome philosophy to have type checking which makes it possible to only provide valid values - so I'm a bit torn.. :slightly_smiling_face: 
But for now I think I lean towards it being enough with the "last known valid values" available in documentation.
(I'm not requesting from anyone to put in the work to add that, I figure it'll get there in due time...)

**Comment by lamine2000** [comment]
Great, so wouldn't it be like the first solution : Ensure consistency in the chariot documentation (all method docs would then specify the constraints if there is)

(That should be easy to fix)

**Comment by tors42** [comment]
Yup, I like that idea a lot!

**Comment by lamine2000** [comment]
Wonderful, I will soon make a pull request if the changes are still to be done.
