### ISSUE TITLE
Add ultrabullet to the Speed enums 

### ISSUE THREAD

**Issue by TBestLittleHelper** [tors42/chariot#6]
https://github.com/tors42/chariot/blob/5c92bbee9c10e7f71b1e607f4c29427713c22192/src/main/chariot/chariot/model/Enums.java#L87

I think it's just about adding ultrabullet in here? Don't think it was intentionally left out.

**Comment by tors42** [comment]
Thanks for reporting!
I'll trigger a 0.0.39
