### ISSUE TITLE
How do you handle nd-json streams? e.g. gamesByIds

### ISSUE THREAD

**Issue by JoKrus** [tors42/chariot#7]
Hi, 

my plan is to create a game stream and add games to it as I create them via the `challenge()` call.

I am having difficulties with understanding on how I should proceed with this. The stream creation call `gameInfosByGameIds` returns a `Many<T>` object which I can only really transfer to a Java Stream.

Now my understanding is that JavaStreams are 'lazy', so only executed when 'closed'.

How can I then handle new objects immediately after they are added to the stream via a seperate Thread and how do I handle the GameInfo updates of an already added game?

I expected something where I can pass a callback function that always executes as soon as the ndjson stream updates on lichess but I am open to any solution that gives me GameInfo updates.

**Comment by tors42** [comment]
Hi,
it sounds like you are on the right track!
One way to process the events from the stream is to have a thread executing the terminal operation stream.forEach(event -> ...).
Every time an event happens, the forEach will trigger.

Maybe this piece of code can help,
https://github.com/teemoo7/bobby/blob/77118281938c79171cfdbdcacc7431291dc8e2d5/src/main/java/ch/teemoo/bobby/lichess/EventHandler.java#L50

Or this piece of code which I've written myself,
https://github.com/tors42/jc/blob/ea93cef0adf6225e5459ab3510a258e76bf7c3d8/src/jc/jc/app/TVFeed.java#L77

Let me know if they make things clearer, or if they add confusion 😅 - then I'll try to come up with some other example.
Cheers!

**Comment by JoKrus** [comment]
Helped wonders, now I just have to get all possible Lichess statusNames somehow but this is part of lichess api and not yours :D

Thanks a lot! Really awesome API design!
