### ISSUE TITLE
No option for unlimited time control

### ISSUE THREAD

**Issue by BrknRules** [tors42/chariot#8]
Just wondering if an unlimited time control when creating challenges is going to be implemented in the future? Unless it already has been and I've missed something.

**Comment by tors42** [comment]
I don't think it is possible to create an unlimited time control game with the [Lichess API](https://lichess.org/api#tag/Challenges/operation/challengeCreate),
so unless Lichess adds an option to do that it won't be possible to add it to any of the client libraries (such as [berserk](https://github.com/ZackClements/berserk) and chariot etc).

The currently slowest time control which the Lichess API (and chariot) allows to set when creating a challenge is 14 days per move.
(I think the "unlimited" time control which is available only on the web site, i.e not via API, is actually implemented as 21 moves per day, but I might be misremembering)

**Comment by BrknRules** [comment]
Ah I see

I had been making unlimited time control games vs the AI with the API just by omitting all of the time control fields and I thought it'd be the same for seeks and challenges, though that doesn't seem to be the case

Thanks for letting me know!
